name: Build Picons srp
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends --no-install-suggests git xz-utils binutils pngquant imagemagick librsvg2-bin jq
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Download channellists
      run: |
        curl -fsSL "https://github.com/picons/channellists/archive/master.tar.gz" | tar xzf - -C "./build-input" --strip-components=1
    - name: Build srp-13e.19e.23e.28e picons
      run: |
        mv ./build-input/13e.19e.23e.28e ./build-input/enigma2
        bash 1-build-servicelist.sh srp
        bash 2-build-picons.sh srp -13e.19e.23e.28e
        rm -rf ./build-input/enigma2
    - name: Upload srp-13e.19e.23e.28e picons
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'build-output/binaries-srp/*'
    - name: Build srp-ziggo picons
      run: |
        mv ./build-input/ziggo ./build-input/enigma2
        bash 1-build-servicelist.sh srp
        bash 2-build-picons.sh srp -ziggo
        rm -rf ./build-input/enigma2
    - name: Upload srp-ziggo picons
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'build-output/binaries-srp/*'
